language: swift
osx_image: xcode10
xcode_sdk: iphonesimulator12.0
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
    
script:
    - set -o pipefail
    - travis_retry xcodebuild -workspace NobodyHackathons.xcodeproj -scheme "AmadeusTests" -destination "platform=iOS Simulator,name=iPhone 6" build-for-testing test | xcpretty

#